---
author:
- Sarah Gaichas, PhD
- Research Fishery Biologist
- Ecosystem Dynamics and Assessment Branch
- Northeast Fisheries Science Center
opening: Dear Drs. Tommasi and Hill,
closing: Sincerely,
address:
- Southwest Fisheries Science Center
- 8901 La Jolla Shores Drive
- La Jolla, CA, 92037-1508

letterhead: letterhead/NEFSCletterhead.pdf
signature: signature/gaichas.pdf
signature-before: -8ex

output: linl::linl
---

I am delighted to submit a recommendation in support of Robert Wildermuth’s application for the Future Seas Fisheries Science and Management Strategy Evaluation (MSE) postdoc position. I have known Robert since early 2015 when he started his PhD program at University of Massachusetts Dartmouth. He became an active member of the International Council for the Exploration of the Seas (ICES) Working Group on the Northwest Atlantic Regional Seas (WGNARS) during our March working group meeting in 2015, when I was a co-chair of the working group. The working group is composed of oceanographers, ecologists, fishery scientists, social scientists, and fishery and ocean managers from the US and Canada. We are both still working group members, and I am now a member of Robert’s PhD advisory committee. 

Robert has both the modeling skills and the people skills necessary for successful MSE, which can be a rare combination. I was particularly impressed by his commitment and quiet tenacity when he participated in the 2015 WGNARS meeting remotely (it was in Canada and travel funding for all but 2 US members was unavailable). Our phone audio setup was poor, making engagement difficult for those not in the room, but Robert hung in there for the full discussion and contributed key insights as our group developed our very first prototype conceptual model for the Georges Bank social-ecological system. Throughout the following year, Robert worked with us at the National Marine Fisheries Service (NMFS) Northeast Fisheries Science Center (NEFSC) to refine the Georges Bank conceptual model (more detail is provided on this interdisciplinary collaboration below). Robert has since become an essential WGNARS member leading multiple projects. In 2016, he completed a loop analysis of the system, which influenced the working group with regard to model complexity and helped organize further qualitative analyses with the full working group. In 2017, Robert outlined Bayesian belief network analysis for the group, a cutting edge method for integrating the diverse information types we had available for ecological, social, and economic components of the Georges Bank system.  His ongoing leadership on these projects has resulted in useful products (both models and peer reviewed papers), a positive outcome for the WGNARS group in particular, and for ecosystem assessment science in general. This field does not have established methods, and Robert’s leadership in analysis of linked social-ecological networks is already paving the way for applying similar approaches in other systems where ecology and human dimensions have yet to be integrated.

Robert’s research is highly relevant to MSE, as well as extremely timely and relevant as NOAA Fisheries works towards operationalizing marine ecosystem-based management.  In particular, it is critical to evaluate models that can be used for MSE linking environmental drivers, ecological interactions, and human dimensions relevant to marine resource management. Robert’s work evaluating management strategies and ecological outcomes using multiple models is directly applicable to ongoing efforts to provide a “worked example” of operational IEA for the Northeast US large marine ecosystem, which informs ecosystem-based fishery management.  Developing MSE capability is a high priority across NOAA Fisheries and in the Northeast Region, and ecosystem-level MSE is of significant interest to fishery managers here. Similarly, characterizing the uncertainty in models and data sources used in assessments—whether single stock, multispecies, or full ecosystem—is considered a best practice for management of living marine resources, but is in its infancy for complex social-ecosystem models. Robert’s work will contribute considerably to better understanding the performance of these tools. Further, the comparison of a highly structured and quantitative tool such as Atlantis with the Bayesian decision network that can accommodate more qualitative inputs opens the door to include information from multiple sources that has previously been underutilized in MSE. Understanding the performance of more qualitative models will benefit both data-poor regions and regions with substantial but unbalanced data resources in developing meaningful MSEs addressing a wide range of objectives. 
 
Robert’s academic qualifications display the diversity as well as the achievement necessary to succeed at MSE. However, Robert’s interest goes well beyond academics. In my experience, Robert has gone out of his way to engage with both agency scientists and resource managers to ensure that interdisciplinary ecosystem science is useful and accessible. This is an essential skill for engaging stakeholders in MSE. Because fishery and ocean managers are only beginning to consider integrated management, providing them with illustrative examples can be a useful way to begin discussions of how to move forward with ecosystem-based management considering the tradeoffs between social, economic, and conservation objectives. Robert’s work has taken the relatively simple Georges Bank ecosystem conceptual model and asks the kind of “what if” questions managers find useful. In particular, his work with model complexity illustrates the importance of including details of the social and economic system (which managers deal with regularly) as well as the ecological system that marine  scientists often focus on. 

Visualizations are especially important for engaging managers and the general public to solve real-world problems. I find Robert’s visualizations of social-ecological networks to be outstanding communication tools; he manages to include the diversity of interacting entities without overwhelming his audience. His work, both on visualization and qualitative loop analysis, contributes directly to the ongoing development of ecosystem-based fishery management protocols in the Northeast. Further, the Bayesian network modeling takes a very practical approach to incorporate available data on important social-ecological system components and will ground truth the model against a more complex model. Robert understands that real-world applications demand the level of rigor that he has built into all of his analyses. 

Including social, economic, and ecological aspects in MSE requires collaboration across a wide range of fields, practices, and even physical locations. Robert has been active in interdisciplinary collaborations within the ICES WGNARS working group, described above, as well as within the National Oceanic and Atmospheric Administration (NOAA) both within the NEFSC (oceanography, ecosystem, protected species, and social sciences branch involvement), across NMFS science centers and other NOAA line offices (Integrated Ecosystem Assessment conceptual modeling working group), and in an international group of marine ecosystem modelers working on a variety of applications (Atlantis summit). In each instance, Robert has shown that he thinks clearly about the issues at hand, is able to see the big picture, and engages with the group to improve the group product, whether it highlights his own particular research topic or not. 

Communication among and between scientific disciplines can be difficult, due both to organizational structure and to technical language and methods, which we encountered during our process for building the Georges Bank conceptual model within NEFSC.  We built sub-models for ecology, physical environment, and human dimensions separately and then merged them as a group, revealing how different thinking and different currencies between disciplines caused some disconnects. However, Robert showed a great deal of patience and commitment to multi-disciplinary work as we smoothed the connections out. In my experience, he could be counted on in each meeting to keep his “eyes on the prize” and keep the group moving forward when diversions happened. 

Given Robert’s current contributions, I have no doubt that his future contributions will continue to advance the field of MSE. Robert’s Bayesian belief network analysis uses a cutting edge method for integrating the diverse information types we have available for ecological, social, and economic components of the Georges Bank system. This field does not have established methods, and Robert’s leadership in analysis of linked social-ecological networks is already paving the way for applying similar approaches in other systems where ecology and human dimensions have yet to be integrated.

To summarize, I have known Robert for only a few years and know only a portion of Robert’s work, so I am sure there is even more that is relevant to this position than I can comment on here. I feel fortunate to be working with him. Robert stands out to me as a clear thinker and communicator with a strong commitment to leading us all towards more and better interdisciplinary science for marine conservation. His dedication to bridging the ecological and human dimensions in modeling and analysis is somewhat rare, and also essential to achieving MSE and ecosystem-based management that works for the real world. I think he is an excellent fit for the Furture Seas MSE postdoc position.

Please do not hesitate to contact me with any questions.

