---
title: 
csl: plos.csl
fontsize: 10pt
output:
  pdf_document:
    includes:
      in_header: latex/midyr-header.tex
    keep_tex: yes
  html_document:
    df_print: paged
link-citations: yes
geometry: left=2cm, right=2cm, top=2cm, bottom=3cm, footskip = .5cm
subparagraph: yes
urlcolor: blue
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# library(magrittr)
# library(scholar)
# library(RefManageR)
# library(vitae)

```

## Element 1: Research (30) 

### Objective: Support the development of ecosystem approaches to fishery management/Integrated Ecosystem Assessment (IEA) and Management Strategy Evaluation (MSE) for the U.S. Northeast Continental Shelf

*1. Conduct research on implementing ecosystem approaches and IEAs.*

*	Continued research related to State of the Ecosystem (SOE) reporting to improve management relevance by including ecosystem conceptual models, aligning indicators with general US IEA objectives, and synthesizing results across indicators.
    + Restructured SOE outline (for both regions) in December 2020 to reinforce indicator linkages to management objectives and to improve synthesis across indicators by emphasizing "multiple drivers" of social-ecological change. 
    + Framed climate indicators and offshore wind development indicators in terms of "risks to meeting fishery management objectives" to improve management relevance.
    + Added "Implications" sections after all indicators to clearly link information to management. 
    + Restructured summary section into a report-card style table linking indicator trends to ecosystem level management objectives. Risks to meeting objectives remain in a bulleted summary list.
* Results: 
    + Both internal reviewers and Council audiences have responded very positively this restructuring, highlighting the improved readability and clear connections across indicators in the report. 
    + The MAFMC SSC is interested in "operationalizing" the SOE information further in decision processes.
    + This structure will be retained in coming years to allow more research effort into indicator thresholds and more quantitative synthesis.

* Continued work with interdisciplinary working groups supporting Integrated Ecosystem Assessments (IEAs). In collaboration with NEFSC EDAB, SSB, PDB, Mid-Atlantic Fishery Management Council (MAFMC) and other staff, September 2020-April 2021:
    +	Supported working group developing EAFM MSE for Mid-Atlantic summer flounder
        + how best to introduce the concept of MSE to new audiences
        + how best to organize virtual stakeholder workshops 
    +	Developed EAFM background materials for MSE stakeholder workshops demonstrating the IEA process and how it has been successfully adapted by the MAFMC

*2. Contribute to the development and implementation of multispecies and ecosystem MSE operating models.*

*	Continued research using Atlantis models as operating models for performance testing assessment models. Expanded research to include both single and multispecies models with US and European colleagues.
    + Evaluation of single species assessments under climate change scenarios with Lynch, Kaplan, Stawitz: “Fragile ecosystems, robust assessments? Performance testing stock assessments for the California Current and Nordic and Barents Seas under climate change”; started with international research fellowship funds in 2019
        + Preliminary results for California Current sardine with Atlantis "data" input in review at Frontiers (see publications in review, Kaplan et al.)
        + Coordinating stock synthesis model for Barents Sea cod with Atlantis "data" input with Norwegian IMR colleagues
        
    + NEFSC Multispecies model comparisons, length structured vs age structured with K. Curti, PDB and G. Fay UMass Dartmouth; internal funds from NERAP/EBFM 
        + 
        + 
        
    + ICES WGSAM multispecies model skill assessment project. 
        + 
        + 
     
* See Element 3, Products: `atlantisom` R package development continues to facilitate all of this work
    
*	Refined and applied model key run review criteria for use in ICES WGSAM multispecies model review. See section 4: reviews (below) for outputs and publication. 

* Initial development of R package for Atlantis model diagnostics: `atlantisdiagnostics`
    + Objective: automatically test whether model meets Atlantis review criteria
    + Package: https://github.com/NOAA-EDAB/atlantisdiagnostics/
    + Progress: https://github.com/NOAA-EDAB/neus-atlantis/tree/master/diagnostics
    + Visualization: https://noaa-edab.github.io/neus-atlantis/DiagnosticsDoc.html

*	Organize and lead monthly ecosystem/multispecies modeling meetings to coordinate modeling projects, progress. Current focus is on ms-keyrun project described above, with updates on other modeling efforts. See [minutes]().

*3. Communicate research results through peer-reviewed manuscripts, reports, and oral/poster presentations at scientific meetings*

* Published

DePiper, G., Gaichas, S., Muffley, B., Ardini, G., Brust, J., Coakley, J., Dancy, K., Elliott, G.W., Leaning, D., Lipton, D., McNamee, J., Perretti, C., Rootes-Murdy, K., Wilberg, M. 2021. Learning by doing: collaborative conceptual modelling as a path forward in ecosystem-based management, ICES Journal of Marine Science, fsab054, https://doi.org/10.1093/icesjms/fsab054 

Muffley, B.,  Gaichas, S., DePiper, G., Seagraves, R., and Lucey, S. 2021. There is no I in EAFM: Adapting Integrated Ecosystem Assessment for Mid-Atlantic Fisheries Management. Coastal Management, 49:1, 90-106, DOI: 10.1080/08920753.2021.1846156

Bastille, K., Hardison, S., DeWitt, L., Brown, J., Samhouri, J.,  Gaichas, S., Lucey, S., Kearney, K., Best, B., Cross, S.,  Large, S., Spooner, E.  2021. Improving the IEA Approach Using Principles of Open Data Science, Coastal Management, 49:1, 72-89, DOI: 10.1080/08920753.2021.1846155

Reum, J., Townsend, H., Gaichas, S., Sagarese, S., Kaplan, I., Grüss, A. 2021. It’s Not the Destination, It’s the Journey: Multispecies Model Ensembles for Ecosystem Approaches to Fisheries Management. Frontiers in Marine Science 8, 75. 26 February 2021. DOI: 10.3389/fmars.2021.631839 

* In Press

Friedland, K., Methratta, E., Gill, A., Gaichas, S., Curtis,T.,  Adams, E., Morano, J., Crear, J., McManus, C., Brady, D. In Press. Resource Occurrence and Productivity in Existing and Proposed Wind Energy Lease Areas on the US Northeast Shelf. Frontiers in Marine Science


* In Revision

Staudinger, M., Lynch, A.,  Gaichas, S., Fox, M., Gibson-Reinemer, D., Langan, J., Teffer, A., Thackeray, S., and Winfield, I.  Submitted April 2020 . How does climate change affect emergent properties of aquatic ecosystems? Fisheries

Kaplan, I.,  Gaichas, S., Stawicz, C., Lynch, P., Marshall, K., Deroba, J., Masi, M., Brodziak, J., Aydin, K.,  Holsman, K., Townsend, H., Tommasi, D., Smith, J.,  Koenigstein,  S., Weijerman, M., Lucey, S., Link, J.  Management Strategy Evaluation: Allowing the Light on the Hill to Illuminate More than One Species. Frontiers in Marine Science


* In Prep

Kempf, A., Lehuta, S., Spence, M.,  Gaichas, S. , .... Skill assessment of models relevant for the implementation of an ecosystem approach to fisheries management.

* Scientific meeting presentations, Sept 2020-April 2021

[US Reference Points Introduction](https://noaa-edab.github.io/presentations/20200921_USrefpts_WKRPchange_Gaichas.html#1), September 21,  2020, ICES Workshop on Reference Point Changes

[Herring HCR accounting for its role as forage](https://noaa-edab.github.io/presentations/20200923_herringWKRPchange_Gaichas.html#1), September 23, 2020, ICES Workshop on Reference Point Changes

[Species Interactions in Multispecies models](https://noaa-edab.github.io/presentations/20201008_FIT_MSmods_Gaichas.html#1), October 8 2020, NOAA Fisheries Integrated Toolbox Technical meeting 

[Multispecies models: US update](https://noaa-edab.github.io/presentations/20201012_WGSAM_USupdate_Gaichas.html#1), October 12, 2020, ICES Working Group on Multispecies Assessments

[Integrating Climate into SOE and Model Skill Assessment](https://docs.google.com/presentation/d/184Af-afIIv-aGSRT6-Ed9SRmqf5n8YOO/edit#slide=id.p1), November 17, 2020, Northeast Fisheries-Climate PI workshop


*4. Review scientific manuscripts, research proposals, and job completion reports as requested.*

* Co-chaired North Sea multispecies model key run reviews for ICES WGSAM, October 2020.
    + all review materials posted online at https://github.com/ices-eg/wg_WGSAM 
    + ICES. 2021. Working Group on Multispecies Assessment Methods (WGSAM; outputs from 2020 meeting). ICES Scientific Reports. 3:10. 231 pp. https://doi.org/10.17895/ices.pub.7695  
* Completed 2 peer reviews for ICES JMS and CJFAS (declined multiple review requests during SOE production January-April 2021).

## Element 2: Program support (10) 

### Objective: Provide analytical support for EDAB and MSE research initiatives

*1.  Provide analytical support for Ecosystem Approaches* 

*	Led State of Ecosystem 2021 report production for Mid-Atlantic Council
*	Contributed single stock status indicator and supported all subgroups for SOE
* Interviewed candidates with K. Curti (PDB) and Gavin Fay (UMass Dartmouth) supported internal NRAP/EBFM funding to support multispecies model development and comparison (also applies to MSE)

*2.  Play lead role in Management Strategy Evaluation for EDAB and coordinate with other Center scientists working on MSE*

* Leading project management for 2021 model key runs ([Jira board](https://www.fisheries.noaa.gov/jira/secure/RapidBoard.jspa?projectKey=KEYRUN&rapidView=384))
* Leading simulated dataset development for 2021 model keyruns
* Coordinating internal MSE working group for MAFMC summer flounder MSE with PDB and SSB staff
* Co-chair of National MSE working group; organized December 2020 meeting, collaborating on national MSE use and prioritization guidelines 

*3.  Serve as mentor for Center staff, graduate students, and post-doctoral researchers as appropriate.*

*	Serve on 2 PhD committees: Robert Wildermuth (SMAST), Jim Gartland (VIMS). 
    +	NMFS mentor for Robert Wildermuth 2018 PopDy Fellowship
* Serve on 1 Masters committee: Aliya Caldwell (UNH)
* Post-doc co-advisor (with V. Saba), Joe Caracappa
* Post-doc consultant (with Kristin Kleisner), Katie Peterson at  ([SESYNC](https://www.sesync.org/users/kpeterson))


## Element 3: Products and Services (30) 

### Objective: Provide accurate and timely information in support of Ecosystem Approaches to Management/Integrated Ecosystem Assessments and Management Strategy Evaluation

*1. Contribute to the development of Ecosystem Approaches and IEA Products and Services on the Northeast US Shelf* 

* Lead editor, State of the Ecosystem Report (Mid-Atlantic)
    +  Supported regular check-in meetings, Sept-December 2020
    +  Developed strawman synthesis, December 2020
    +  Presented strawman, structured and participated in synthesis workshop Jan 2021
    +  Provided draft document for collaborative editing Jan 2021
    +  Transferred to rmarkdown for pdf production, edited
    +  Finalized table, text, and alt-text for 3 page summary
    +  Provided feedback to graphic artist for 3 page summary
    +  Submitted to internal review Feb 2021
    +  Wrote new "request tracking memo" detailing all 2019-20 requests and resulting SOE changes, memop applies to both Mid-Atlantic and New England reports
    +  Completed internal review edits and submitted to Council SSC for review
    +  Collaborated on SOE web story and website resource wrapper
    +  Developed presentations and [presented to SSC](), March 2020
    +  Revised documents based on SSC feedback and submitted to Council, March 2020
    +  Provided assistance with New England report development process as needed
    +  Developed presentation and presented to Mid-Atlantic Council, April 2020
  
* Lead editor, Mid Atlantic EAFM Risk Assessment
    +  Updated portions of the risk assessment based on SOE 2021 indicators
    +  Incorporated updated management indicators from Council staff
    +  Suggested additional indicators and considerations for MAFMC
    +  Developed new [integrated presentation of SOE and Risk assessment](), and presented Mid-Atlantic Council, April 2021
    

*2. Contribute to the development of Management Strategy Evaluation Products and Services on the Northeast US Shelf*

* Core member, Mid-Atlantic EAFM MSE technical team with SSB, PDB, MAFMC staff
    + Support MAFMC in first full stakeholder MSE (and first under EAFM policy)
    + Developed plans for stakeholder survey and stakeholder workshops
    + Presented and participated in all stakeholder workshops to date (see above)
    + Based on initial feedback, will help prioritize which aspects need models and how to link them with SSB-PDB led modeling team

* Collaborating with G.Fay UMassD to develop estimation capabilities for the length-structured multispecies model hydra. Working in the [hydra-sim](https://github.com/thefaylab/hydra_sim) codebase to keep the simulation model and estimation models compatible.
    + Completed documentation with coding in progress for objective function.
    + Modifying Andy Beet's [`hydradata`](https://github.com/thefaylab/hydradata) package to write [hydra inputs](https://github.com/NOAA-EDAB/ms-keyrun/tree/master/simulated-data/msinput/hydra).

* `atlantisom` R package development continues: create assessment model performance testing datasets from Atlantis model output, now providing input to SS3 stock assessment model with S&T and NWFSC colleagues, SAM model input in progress with IMR colleagues, inputs to multiple multispecies models in progress with ICES WGSAM colleagues
    +	Package: https://github.com/r4atlantis/atlantisom
    + Draft landing page: https://sgaichas.github.io/poseidon-dev/atlantisom_landingpage.html
    +	Development notes: https://github.com/sgaichas/poseidon-dev
    + Developed multiple capabilities in FY 2021
        + [Multiple surveys](https://sgaichas.github.io/poseidon-dev/msSurveysTest.html) can be simulated and all produce biomass index, age composition, length composition, and mean weight-at-age data for full true age structure or Atlantis age classes. Fishery catch and discard data is also available by true age. These are essential input into single and multispecies assessment models.
        + [Diet data](https://sgaichas.github.io/poseidon-dev/SurveyDietCompTest.html) can be sampled by the survey, with user specified bias and variance. 
        + Users can apply wrapper functions to get basic data as demonstrated in above vignettes
        + Datasets have been generated for a multispecies production production model ([MSSPM data](https://github.com/NOAA-EDAB/ms-keyrun/tree/master/simulated-data/msinput/msspm)) and are in progress for hydra (see above) at present. Code to produce datasets currently in [ms-keyrun vignette](https://noaa-edab.github.io/ms-keyrun/SimData.html) but will be ported to functions in `atlantisom` or another helper pacakge.
       

## Element 4: Planning and evaluation (20) 

### Objective: Planning and Evaluation for Ecosystem Approaches and Management Strategy Evaluation

*1. Serve on committees, steering groups and task forces* 

* MAFMC Scientific and Statistical Committee: establishes Acceptable Biological Catches for managed Mid-Atlantic fisheries. Next (virtual) meeting scheduled for May 2020. Providing meeting summary reports to NEFSC leadership, Assigned lead: blueline tilefish; on committee developing approach to estimating level of scientific uncertainty in overfishing limits (OFL CV subcommittee), and participated in the Economics working group until March 2021. 
*	MAFMC’s Ecosystem Approach to Fisheries Management Working Group; see above for contributions (currently MSE and ongoing SOE and risk assessment updates).
* National Ecosystem monthly call NEFSC co-representative
*	National MSE working group co-chair:  see above for responsibilities. 
*	Steering committee member, PAradigm for New Dynamic Ocean Resource Assessments and exploitation (PANDORA), EU project
* NE IEA quarterly meeting participant

*2. Actively promote interactions between the Ecosystem Assessment Program with other Center Divisions, the Center Directorate, and the interested public. Actively promote interdisciplinary MSE within and beyond the Center*

*Scientist interactions*  

*	Member and current co-chair of ICES WGSAM (member 2011-present, co chair since 2016), which reviews and contributes to multispecies and ecosystem modeling progress across the ICES regions (the North Sea, Baltic Sea, Bay of Biscay, Mediterranean, Iceland, Barents/Norwegian Seas, and eastern USA). 
    + Developed agenda and co-chaired October 2020 virtual meeting
    + Provided US updates collected from around the nation
    + Finalized 2020 report (model reviews) on schedule for North Sea assessment working groups
*	Member and past co-chair of ICES WGNARS (2012-present), developing ecosystem indicators and integrated ecosystem assessments for Canadian and U.S. marine ecosystems.
    + likey to update ICES WGNARS on SOE and Council updates in 2021
    + 2021 meeting scheduled for 
*	See multiple national and regional ecosystem and MSE working group responsibilities above.
* Provide briefings to Center Directorate on Council agenda items as requested
*	Active ongoing collaborations between NEFSC EDAB and SSB, PSB, OCB for IEA work 
* Supporting *Illex* ecosystem indicators project led by K. Hyde with PDB and CRB colleagues
*	Affiliate Faculty at SMAST, April 2016-present
* Participated in ACLIM workshop on ensemble modeling with AFSC/UW
* Attended NPFMC SSC February meeting on ecosystem risk indicators for stock assessment, provided info on MAFMC SSC OFL CV approach
*	Continuing collaboration with AFSC on development of food web models in R. 
*	Continuing collaboration on COCA MSE project with GMRI/SMAST 
    +	Consulting on multiple groundfish models 
    + Facilitating collaboration between COCA postdocs and NEFSC scientists including Min-Yang Lee (SSB) and Anna Birkenbach (U. Delaware).
*	Continuing collaboration on seabirds/fishery management postdoc project with Gemma Clucas at Cornell
* Previously scheduled meetings/presentations now rescheduled:
    + NMFS Atlantic Coast Science Coordination Workshop, virtual, August 2021
    + Multispecies Modeling in Support of Fishery Management Workshop, virtual, June 2021
\
*Fishermen/Industry interactions* 

* Calls discussing forage management in Mid-Atlantic with stakeholders on request (2)

*3. Interact with stakeholders to disseminate knowledge via courses, seminars, lectures and workshops as appropriate*

* [Chesapeake Bay Fishery Goal Implementation Team](), January 2021
* [DFO EBFM working group](), February 2021
* MAFMC MSE workshops, presented introduction to MAFMC EAFM, risk assessment, and conceptual modeling results, also acted as breakout group note-taker, facilitator as requested
    + Council committees and advisors in September 2020, [EAFM intro]()
    + Regional stakeholder workhops March-April 2021 (3), [EAFM intro]()
* [Stockton college marine science course](), presented info on SOE and modeling, March 2021
* [MAFMC SOE and risk assessment]()
    

* Shoals Marine Lab IEA virtual course scheduled for July 2021, will lecture on ecosystem modeling and run a lab


## Element 5: Corporate Responsibility, Training, and Professionalism (10)

### Objective: support a safe, secure, and productive workplace; follow required policies and procedures; enhance professional knowledge and skills in support of organizational performance; and promote positive interactions with coworkers, partners, and the public

*1. Safety and Security.  Foster a safe and secure work environment, including complying with agency safety and security, environmental compliance, and IT security policies, plans, and requirements.  Keep work areas free of known hazards and comply with all occupational safety requirements.  Promptly report all known and suspected safety problems to supervisor. * 

* Complied with agency safety and security policies.
* Complied with IT security policies.
* Work areas are free of known hazards. No safety problems to report yet this year.

*2. Policies.  Adhere to DOC, NOAA, NMFS, and SF policies and procedures (e.g., Records Management, T&A, and Telework) and complete required training by established deadlines.  Maintain accountability of assigned government property and report lost property promptly.  Follow NOAA IT policies including directives in “Appropriate Use of Government Equipment.” Comply with travel regulations and policies, including proper use of the government travel cards.  Ensure sensitive Personally Identifiable Information and Business Identifiable Information, both physical and electronic, is protected from unauthorized release, alteration, loss and deletion, and complies with security and privacy policies regarding access to computerized and paper files.*

* Completed required training well before deadlines. 
* Reported all government property upon request. 
* Followed IT equipment and travel policies (no travel yet this FY). 
* Followed all PII and BII procedures (I rarely work with this type of data).

*3.  Professional Development.  In coordination with supervisor, complete identified opportunities for training and professional development beyond mandatory training requirements to maintain and/or develop professional knowledge and skills.  Provide appropriate documentation of completion of training to supervisor and complete training-related reporting requirements.  Discuss outcomes with supervisor and, as appropriate, share knowledge learned with colleagues.*

* I'm trying to incorporate more automation and open science principles into my daily workflow. This involves trying new R packages for interactive presentations and document writing as well as data wrangling and analysis. 
* I'm also trying to learn more formal project management methods, and have both taken online Jira training and recommended it to others. I now regularluy use Jira for the ms-keyrun project. 
* Seaside chats are providing many opportunities for professional development. I have participate in nearly all of them this FY.
* South Coast UseR group has also provided many opportunities to improve R workflows. I have shared these invites with EDAB when appropriate. 
* I participate in University of Washington School of Fisheries Think Tanks (scientific workshops) and quantitative seminars when the topic is relevant, and have also shared these invites with EDAB.

*4.  Teamwork and Cooperation.  Foster a respectful and inclusive workplace and contribute positively to the office and the agency.   Respond in an appropriate and timely manner to changes in work priorities.  Participate constructively in teams and cross-cutting efforts in support of the office or agency.  Foster teamwork and cooperation by sharing information and expertise.*

* I'm finding google chat helpful to work with our team remotely. I prioritize group meetings and team projects such as the SOE and try to give timely input.
* I work on IEA and MSE teams across branches and divisions within NEFSC, and co-chair the national MSE working group (see Element 4, point 2).

*5.  Professional Conduct.  Follow agency professional conduct, diversity, ethics, and EEO policies.   Exhibit competency, integrity, good judgment, and courtesy when interacting with colleagues and the public.*

* Trying my best.